@Findgroup_Backend_HostAddress = http://localhost:5110

GET {{Findgroup_Backend_HostAddress}}/
Accept: application/json

###

GET {{Findgroup_Backend_HostAddress}}/
Accept: application/json

###

GET {{Findgroup_Backend_HostAddress}}/api/User
Accept: application/json
###
POST {{Findgroup_Backend_HostAddress}}/api/Auth/register
Content-Type: application/json
{
  "Username" : "TestUser",
  "Email" : "TestUser@gmail.com",
  "Password" : "Passwd123$"
}

###

PUT {{Findgroup_Backend_HostAddress}}/api/User/125e3616-3af4-44f5-922a-625a37ba80e9
Content-Type: application/json

{
  "Id" : "125e3616-3af4-44f5-922a-625a37ba80e9",
  "UserName" : "Modified Jane",
  "Email" : "janedoe@gmail.com",
  "PhoneNumber" : "+3611111111"
 
}

###

DELETE {{Findgroup_Backend_HostAddress}}/api/User/2cc162c3-3df8-4a0a-948b-680add05b295
Content-Type: application/json

###

POST {{Findgroup_Backend_HostAddress}}/api/Auth/login
Content-Type: application/json
{
  "Username" : "TestUser",
  "Password" : "Passwd123$"
}
###

GET {{Findgroup_Backend_HostAddress}}/api/Home/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdFVzZXIiLCJqdGkiOiI0NWZlMGQ2OC04MjFiLTQ0NzktYjY2OS03OTY5MDY4MzZmNTIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImEzYjcyNTAyLTQ5Y2MtNDUwMy1iZmVlLTFkMGE3YzE5ZWY0NyIsImV4cCI6MTczODc0OTM5NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiYXVkIjoiZmcuZ2cifQ.DLmYg7Mxwdh7yKaogVgAyY4lyq4ogeorIYJ-wAFCKLU
###