@Findgroup_Backend_HostAddress = http://localhost:5110

GET {{Findgroup_Backend_HostAddress}}/
Accept: application/json

###

GET {{Findgroup_Backend_HostAddress}}/
Accept: application/json

###

GET {{Findgroup_Backend_HostAddress}}/api/User
Accept: application/json
###
POST {{Findgroup_Backend_HostAddress}}/api/Auth/register
Content-Type: application/json
{
  "Username" : "TestUser1",
  "Email" : "TestUser1@gmail.com",
  "Password" : "Passwd123$"
}

###

PUT {{Findgroup_Backend_HostAddress}}/api/User/125e3616-3af4-44f5-922a-625a37ba80e9
Content-Type: application/json

{
  "Id" : "125e3616-3af4-44f5-922a-625a37ba80e9",
  "UserName" : "Modified Jane",
  "Email" : "janedoe@gmail.com",
  "PhoneNumber" : "+3611111111"
 
}

###

DELETE {{Findgroup_Backend_HostAddress}}/api/User/2cc162c3-3df8-4a0a-948b-680add05b295
Content-Type: application/json

###

POST {{Findgroup_Backend_HostAddress}}/api/Auth/login
Content-Type: application/json
{
  "Username" : "TestUser1",
  "Password" : "Passwd123$"
}
###

GET {{Findgroup_Backend_HostAddress}}/api/Home/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdFVzZXIiLCJqdGkiOiI0NWZlMGQ2OC04MjFiLTQ0NzktYjY2OS03OTY5MDY4MzZmNTIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImEzYjcyNTAyLTQ5Y2MtNDUwMy1iZmVlLTFkMGE3YzE5ZWY0NyIsImV4cCI6MTczODc0OTM5NCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiYXVkIjoiZmcuZ2cifQ.DLmYg7Mxwdh7yKaogVgAyY4lyq4ogeorIYJ-wAFCKLU
###

POST {{Findgroup_Backend_HostAddress}}/api/Post 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdFVzZXIiLCJqdGkiOiJhZjEzNGViOC02MDljLTRmZjctOTFlMy00MjIwZWQ0Yjg4YzIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZkZGVlNGQ5LTY0ODAtNDI4NS05ZTMyLTBmMmRhODM2ODAyMyIsImV4cCI6MTczOTE5MDIwMywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MTEwIiwiYXVkIjoiZmcuZ2cifQ.MaIqMSgp20RpaPh48VdbzAgFkmtV71PUf6IDTbvgTeQ
{
  "Title": "My first post!!",
  "Content" : "Need some ppl in league btw",
  "CategoryId" : 1,
}
###

GET {{Findgroup_Backend_HostAddress}}/api/Post 
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiVGVzdFVzZXIxIiwianRpIjoiNGU2NzQ4NjktZDllYy00MWM2LTlkZjctNzZhY2Q5MTM0MjA4IiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiJiZWUyMzE0NS03OTFmLTQwODItOTRmNS1jNjdjNDNlMjEzM2EiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwiZXhwIjoxNzM5MjgwMDcyLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUxMTAiLCJhdWQiOiJmZy5nZyJ9.KGxU1hqjU1K38lfKjTCfYddSdoBbikZVj23G37yI9vc
